### ISSUE TITLE
Use Markdown instead of PDF

### ISSUE THREAD

**Issue by sinadarvi** [ubuntu-ir/iranFSFplan#2]
Hi, it's a better idea to use a markdown file instead of PDF, so we can have a history of what we and others changed

**Comment by mtashackori** [comment]
به محض اینکه نسخه قابل ویرایشش رو پیدا کنم حتما

**Comment by mtashackori** [comment]
iranFSFplan/FOSS Migration_RPT_1_Sanad Review_v3_900825.docx
      برای ویرایش میتوانید از نسخه لینک فوق استفاده کنید
